[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "./railway_deploy.sh"
# Use a simple health check path that doesn't require external services
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
