[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["backend/**", "Dockerfile", "railway_deploy.sh", "*.toml", "*.sh", "requirements.txt", "*.py"]

[deploy]
startCommand = "./railway_deploy.sh"
# Use a simple health check path that doesn't require external services
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
